services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: ["--nginx.scrape-uri=http://nginx:8081/stub_status"]
    networks: [frontend]
    depends_on: [nginx]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks: [frontend]
    depends_on: [nginx-exporter]
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:12.4
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/network-lab.json
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks: [frontend]
    depends_on: [prometheus]
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
